### ISSUE TITLE
Projet incomplet

### ISSUE THREAD

**Issue by eamosse** [arabadan/bibliotheque_ntdp#1]
Je n'ai pas retrouvé la partie client de votre projet
Vous n'avez pas communiqué les autres membres du groupe

**Comment by arabadan** [comment]
Bonsoir,

Nous avons une branche webapp sur le d?p?t Git,

Cordialement,
Bonne soir?e

Andy Rabadan

T?l?charger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by eamosse** [comment]
Merci de m'envoyer le nom des autres membres du groupe.  Autrement, je considerai que tu as fait le projet seul.

**Comment by arabadan** [comment]
Nous sommes 2, Quentin Bauer et moi

T?l?charger Outlook pour Android<https://aka.ms/ghei36>

________________________________
